pluginManagement {
    plugins {
        id 'org.springframework.boot' version '3.5.3'
        id 'io.spring.dependency-management' version '1.1.7'
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}
rootProject.name = 'janggunkitchen'

include 'backend:app'
include 'backend:database-migrations'
